# Generated by Django 4.1 on 2023-03-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Kategorie',
        ),
    ]
