# Generated by Django 4.1 on 2023-04-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_kategorie_options_produkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
