# Generated by Django 4.1 on 2023-04-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_produkt_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='is_sold',
        ),
    ]
